### ISSUE TITLE
Can't configure getAll to use parameter in the url

### ISSUE THREAD

**Issue by daniil-omelchenko** [dsternlicht/RESTool#131] opened 2020-05-22 23:34 UTC
Can't figure out how to navigate through hierarchies.

Hor example I have the following page config:
```
page: {
    name: 'Revisions',
    id: 'revisions',
    description: 'Manage search entity revisions',
    methods: {
        getAll: {
            url: '/entities/:entityId/revisions',
               queryParams: [
                   {
                       label: 'ID',
                       name: 'entityId',
                       type: 'text',
                       required: true
                    }
                ],
...
}
```

With the URL: `<base>/#/revisions?entityId=123` I'd expect for getAll request have URL: `<api>/entities/123/revisions` instead I end up with: `<api>/entities/:entityId/revisions?entityId=123`

Could anyone help?

**Comment by dsternlicht** [comment] 2020-05-23 17:47
@daniil-omelchenko It looks like you're trying to create one to many page. There's an active PR for this, as at the moment RESTool don't support it.

https://github.com/dsternlicht/RESTool/pull/119

**Comment by dsternlicht** [comment] 2020-05-23 17:48
Duplicate of #115

**Closed** 2020-05-23 17:48 UTC
